version: '3.8'

services:
  youtube-downloader:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - FLASK_DEBUG=false
      - MONGODB_URI=${MONGODB_URI}
      - BOT_TOKEN=${BOT_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - SESSION_SECRET=${SESSION_SECRET}
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3